spring.application.name=Uber

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Configuration (from .env)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis Configuration (from .env)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}