plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.hilt)
    kotlin("kapt")
}

android {
    namespace = "com.rideorbit.auth"
    compileSdk = 35
    defaultConfig { minSdk = 26 }
}

dependencies {
    implementation(project(":core-network"))

    // Google Sign-In
    implementation(libs.google.signin)

    // DI
    implementation(libs.hilt.android)
    kapt(libs.hilt.compiler)
}
