pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "RideOrbit-Android"

include(":app-passenger")
include(":app-driver")
include(":core-network")
include(":core-models")
include(":core-maps")
include(":core-auth")
